import { Inter } from "next/font/google";
import "./globals.css";
import  "bootstrap/dist/css/bootstrap.min.css"
import AddBootstrap from "./AddBootstrap";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="https://kit.fontawesome.com/c24df95af8.js" crossOrigin="anonymous"></script>        
      </head>
      <body className={inter.className}>
      <AddBootstrap/>
      {children}
      </body>
    </html>
  );
}
